blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/Lightning-AI/torchmetrics/discussions/new
    about: Ask and answer TorchMetrics related questions
  - name: ðŸ’¬ Slack
    url: https://app.slack.com/client/TR9DVT48M/CQXV8BRH9/thread/CQXV8BRH9-1591382895.254600
    about: Chat with our community
