on: # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "requirements/*"
      - ".devcontainer/*"
      - "environment.yml"
      - "requirements.txt"
      - ".github/workflows/*docker*.yml"
      - "setup.py"

jobs:
  build-PL:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.6", "3.7", "3.8"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Devcontainer Docker
        # publish master/release
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VARIANT=${{ matrix.python_version }}
          file: .devcontainer/Dockerfile
          push: false
        timeout-minutes: 50
