name: CI action schema
on: # Trigger the workflow on push or pull request, but only for the master branch
  push: {}
  pull_request:
    branches: [master, "release/*"]

jobs:
  validate-schema:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pkg
        run: |
          pip install "check-jsonschema>=0.10"

      - name: GH Workflows
        run: |
          check-jsonschema .github/workflows/*.yml --builtin-schema "github-workflows"
          check-jsonschema .github/actions/*/*.yml --builtin-schema "github-actions"

      - name: Azure Pipelines
        run: |
          check-jsonschema .azure/*.yml --schemafile "https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/v1.188.1/service-schema.json"
