name: "Pull Request Labeler"
on: [pull_request_target]

jobs:
  triage-prs:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # Uploads repository content to the runner
    - uses: actions/checkout@v3
    - uses: actions/labeler@v4
      with:
        # The path to the label configuration file.
        configuration-path: .github/labeling-config.yml
        # Whether removing labels when matching files are reverted or no longer changed by the PR
        sync-labels: true
